<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\CechyPojazdu;

class CechyPojazduTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $poczatkoweDane = [
            ['marka' => 'Toyota', 'model' => 'Corolla', 'nadwozie' => 'Sedan'],
            ['marka' => 'Toyota', 'model' => 'Corolla', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Toyota', 'model' => 'Yaris', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Toyota', 'model' => 'Camry', 'nadwozie' => 'Sedan'],
            ['marka' => 'Toyota', 'model' => 'RAV4', 'nadwozie' => 'SUV'],
            ['marka' => 'Toyota', 'model' => 'C-HR', 'nadwozie' => 'SUV'],
            ['marka' => 'Toyota', 'model' => 'Highlander', 'nadwozie' => 'SUV'],
            ['marka' => 'Toyota', 'model' => 'Sienna', 'nadwozie' => 'Van'],
            ['marka' => 'Toyota', 'model' => 'Tacoma', 'nadwozie' => 'Pickup'],
            ['marka' => 'Toyota', 'model' => 'Prius', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Toyota', 'model' => 'Avalon', 'nadwozie' => 'Sedan'],
            ['marka' => 'Honda', 'model' => 'Civic', 'nadwozie' => 'Sedan'],
            ['marka' => 'Honda', 'model' => 'Civic', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Honda', 'model' => 'Accord', 'nadwozie' => 'Sedan'],
            ['marka' => 'Honda', 'model' => 'Accord', 'nadwozie' => 'Coupe'],
            ['marka' => 'Honda', 'model' => 'CR-V', 'nadwozie' => 'SUV'],
            ['marka' => 'Honda', 'model' => 'HR-V', 'nadwozie' => 'SUV'],
            ['marka' => 'Honda', 'model' => 'Pilot', 'nadwozie' => 'SUV'],
            ['marka' => 'Honda', 'model' => 'Fit', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Honda', 'model' => 'Odyssey', 'nadwozie' => 'Van'],
            ['marka' => 'Honda', 'model' => 'Ridgeline', 'nadwozie' => 'Pickup'],
            ['marka' => 'Ford', 'model' => 'Focus', 'nadwozie' => 'Sedan'],
            ['marka' => 'Ford', 'model' => 'Focus', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Ford', 'model' => 'Fiesta', 'nadwozie' => 'Sedan'],
            ['marka' => 'Ford', 'model' => 'Fiesta', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Ford', 'model' => 'Fusion', 'nadwozie' => 'Sedan'],
            ['marka' => 'Ford', 'model' => 'Fusion', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Ford', 'model' => 'Mustang', 'nadwozie' => 'Coupe'],
            ['marka' => 'Ford', 'model' => 'Mustang', 'nadwozie' => 'Convertible'],
            ['marka' => 'Ford', 'model' => 'Escape', 'nadwozie' => 'SUV'],
            ['marka' => 'Ford', 'model' => 'Explorer', 'nadwozie' => 'SUV'],
            ['marka' => 'Chevrolet', 'model' => 'Malibu', 'nadwozie' => 'Sedan'],
            ['marka' => 'Chevrolet', 'model' => 'Cruze', 'nadwozie' => 'Sedan'],
            ['marka' => 'Chevrolet', 'model' => 'Impala', 'nadwozie' => 'Sedan'],
            ['marka' => 'Chevrolet', 'model' => 'Spark', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Chevrolet', 'model' => 'Sonic', 'nadwozie' => 'Sedan'],
            ['marka' => 'Chevrolet', 'model' => 'Volt', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Chevrolet', 'model' => 'Camaro', 'nadwozie' => 'Coupe'],
            ['marka' => 'Chevrolet', 'model' => 'Camaro', 'nadwozie' => 'Convertible'],
            ['marka' => 'Chevrolet', 'model' => 'Equinox', 'nadwozie' => 'SUV'],
            ['marka' => 'Chevrolet', 'model' => 'Traverse', 'nadwozie' => 'SUV'],
            ['marka' => 'Volkswagen', 'model' => 'Golf', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Volkswagen', 'model' => 'Passat', 'nadwozie' => 'Sedan'],
            ['marka' => 'Volkswagen', 'model' => 'Jetta', 'nadwozie' => 'Sedan'],
            ['marka' => 'Volkswagen', 'model' => 'Tiguan', 'nadwozie' => 'SUV'],
            ['marka' => 'Volkswagen', 'model' => 'Atlas', 'nadwozie' => 'SUV'],
            ['marka' => 'Volkswagen', 'model' => 'Arteon', 'nadwozie' => 'Sedan'],
            ['marka' => 'Volkswagen', 'model' => 'Beetle', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Volkswagen', 'model' => 'Touareg', 'nadwozie' => 'SUV'],
            ['marka' => 'Volkswagen', 'model' => 'ID.4', 'nadwozie' => 'SUV'],
            ['marka' => 'Volkswagen', 'model' => 'Up', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Audi', 'model' => 'A1', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Audi', 'model' => 'A3', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Audi', 'model' => 'A4', 'nadwozie' => 'Sedan'],
            ['marka' => 'Audi', 'model' => 'A5', 'nadwozie' => 'Coupe'],
            ['marka' => 'Audi', 'model' => 'A6', 'nadwozie' => 'Sedan'],
            ['marka' => 'Audi', 'model' => 'A7', 'nadwozie' => 'Sedan'],
            ['marka' => 'Audi', 'model' => 'Q3', 'nadwozie' => 'SUV'],
            ['marka' => 'Audi', 'model' => 'Q5', 'nadwozie' => 'SUV'],
            ['marka' => 'Audi', 'model' => 'Q7', 'nadwozie' => 'SUV'],
            ['marka' => 'Audi', 'model' => 'TT', 'nadwozie' => 'Coupe'],
            ['marka' => 'BMW', 'model' => '1 Series', 'nadwozie' => 'Hatchback'],
            ['marka' => 'BMW', 'model' => '3 Series', 'nadwozie' => 'Sedan'],
            ['marka' => 'BMW', 'model' => '5 Series', 'nadwozie' => 'Sedan'],
            ['marka' => 'BMW', 'model' => 'X1', 'nadwozie' => 'SUV'],
            ['marka' => 'BMW', 'model' => 'X3', 'nadwozie' => 'SUV'],
            ['marka' => 'BMW', 'model' => 'X5', 'nadwozie' => 'SUV'],
            ['marka' => 'BMW', 'model' => 'X7', 'nadwozie' => 'SUV'],
            ['marka' => 'BMW', 'model' => '2 Series', 'nadwozie' => 'Coupe'],
            ['marka' => 'BMW', 'model' => '4 Series', 'nadwozie' => 'Coupe'],
            ['marka' => 'BMW', 'model' => '6 Series', 'nadwozie' => 'Coupe'],
            ['marka' => 'Hyundai', 'model' => 'Sonata', 'nadwozie' => 'Sedan'],
            ['marka' => 'Hyundai', 'model' => 'i30', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Hyundai', 'model' => 'Elantra', 'nadwozie' => 'Sedan'],
            ['marka' => 'Hyundai', 'model' => 'Veloster', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Hyundai', 'model' => 'Tucson', 'nadwozie' => 'SUV'],
            ['marka' => 'Hyundai', 'model' => 'Santa Fe', 'nadwozie' => 'SUV'],
            ['marka' => 'Hyundai', 'model' => 'Kona', 'nadwozie' => 'SUV'],
            ['marka' => 'Hyundai', 'model' => 'Ioniq', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Hyundai', 'model' => 'Accent', 'nadwozie' => 'Sedan'],
            ['marka' => 'Hyundai', 'model' => 'Venue', 'nadwozie' => 'SUV'],
            ['marka' => 'Tesla', 'model' => 'Model S', 'nadwozie' => 'Sedan'],
            ['marka' => 'Tesla', 'model' => 'Model 3', 'nadwozie' => 'Sedan'],
            ['marka' => 'Tesla', 'model' => 'Model X', 'nadwozie' => 'SUV'],
            ['marka' => 'Tesla', 'model' => 'Model Y', 'nadwozie' => 'SUV'],
            ['marka' => 'Tesla', 'model' => 'Roadster', 'nadwozie' => 'Cabrio'],
            ['marka' => 'Tesla', 'model' => 'Cybertruck', 'nadwozie' => 'Pickup'],
            ['marka' => 'Tesla', 'model' => 'Semi', 'nadwozie' => 'Truck'],
            ['marka' => 'Tesla', 'model' => 'Compact', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Tesla', 'model' => 'Tesla van', 'nadwozie' => 'Van'],
            ['marka' => 'Land Rover', 'model' => 'Range Rover', 'nadwozie' => 'SUV'],
            ['marka' => 'Land Rover', 'model' => 'Range Rover Evoque', 'nadwozie' => 'SUV'],
            ['marka' => 'Land Rover', 'model' => 'Range Rover Velar', 'nadwozie' => 'SUV'],
            ['marka' => 'Land Rover', 'model' => 'Range Rover Classic', 'nadwozie' => 'SUV'],
            ['marka' => 'Land Rover', 'model' => 'Range Rover Sport', 'nadwozie' => 'SUV'],
            ['marka' => 'Land Rover', 'model' => 'Range Rover Sport SVR', 'nadwozie' => 'SUV'],
            ['marka' => 'Land Rover', 'model' => 'Defender', 'nadwozie' => 'SUV'],
            ['marka' => 'Land Rover', 'model' => 'Discovery', 'nadwozie' => 'SUV'],
            ['marka' => 'Land Rover', 'model' => 'Discovery Sport', 'nadwozie' => 'SUV'],
            ['marka' => 'Land Rover', 'model' => 'Freelander', 'nadwozie' => 'SUV'],
            ['marka' => 'Mazda', 'model' => '2', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Mazda', 'model' => '3', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Mazda', 'model' => '5', 'nadwozie' => 'MPV'],
            ['marka' => 'Mazda', 'model' => '6', 'nadwozie' => 'Sedan'],
            ['marka' => 'Mazda', 'model' => 'CX-3', 'nadwozie' => 'SUV'],
            ['marka' => 'Mazda', 'model' => 'CX-5', 'nadwozie' => 'SUV'],
            ['marka' => 'Mazda', 'model' => 'CX-9', 'nadwozie' => 'SUV'],
            ['marka' => 'Mazda', 'model' => 'CX-30', 'nadwozie' => 'SUV'],
            ['marka' => 'Mazda', 'model' => 'MX-5', 'nadwozie' => 'Cabrio'],
            ['marka' => 'Mazda', 'model' => 'RX-8', 'nadwozie' => 'Coupe'],
            ['marka' => 'Volvo', 'model' => 'S60', 'nadwozie' => 'Sedan'],
            ['marka' => 'Volvo', 'model' => 'S90', 'nadwozie' => 'Sedan'],
            ['marka' => 'Volvo', 'model' => 'V60', 'nadwozie' => 'Wagon'],
            ['marka' => 'Volvo', 'model' => 'V90', 'nadwozie' => 'Wagon'],
            ['marka' => 'Volvo', 'model' => 'XC40', 'nadwozie' => 'SUV'],
            ['marka' => 'Volvo', 'model' => 'XC60', 'nadwozie' => 'SUV'],
            ['marka' => 'Volvo', 'model' => 'XC90', 'nadwozie' => 'SUV'],
            ['marka' => 'Volvo', 'model' => 'C30', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Volvo', 'model' => 'V40', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Volvo', 'model' => 'V40 Cross Country', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Abarth', 'model' => '595', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Abarth', 'model' => '124 Spider', 'nadwozie' => 'Cabrio'],
            ['marka' => 'Abarth', 'model' => '695', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Abarth', 'model' => '500X', 'nadwozie' => 'SUV'],
            ['marka' => 'Abarth', 'model' => '595C', 'nadwozie' => 'Cabrio'],
            ['marka' => 'Seat', 'model' => 'Ibiza', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Seat', 'model' => 'Leon', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Seat', 'model' => 'Arona', 'nadwozie' => 'SUV'],
            ['marka' => 'Seat', 'model' => 'Ateca', 'nadwozie' => 'SUV'],
            ['marka' => 'Seat', 'model' => 'Tarraco', 'nadwozie' => 'SUV'],
            ['marka' => 'Seat', 'model' => 'Toledo', 'nadwozie' => 'Sedan'],
            ['marka' => 'Seat', 'model' => 'Alhambra', 'nadwozie' => 'MPV'],
            ['marka' => 'Seat', 'model' => 'Mii', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Seat', 'model' => 'Exeo', 'nadwozie' => 'Sedan'],
            ['marka' => 'Seat', 'model' => 'Cupra Formentor', 'nadwozie' => 'SUV'],
            ['marka' => 'Skoda', 'model' => 'Octavia', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Skoda', 'model' => 'Fabia', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Skoda', 'model' => 'Superb', 'nadwozie' => 'Sedan'],
            ['marka' => 'Skoda', 'model' => 'Kodiaq', 'nadwozie' => 'SUV'],
            ['marka' => 'Skoda', 'model' => 'Karoq', 'nadwozie' => 'SUV'],
            ['marka' => 'Skoda', 'model' => 'Scala', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Skoda', 'model' => 'Yeti', 'nadwozie' => 'SUV'],
            ['marka' => 'Skoda', 'model' => 'Rapid', 'nadwozie' => 'Sedan'],
            ['marka' => 'Skoda', 'model' => 'Citigo', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Skoda', 'model' => 'Enyaq', 'nadwozie' => 'SUV'],
            ['marka' => 'Peugeot', 'model' => '208', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Peugeot', 'model' => '208', 'nadwozie' => 'SUV'],
            ['marka' => 'Peugeot', 'model' => '308', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Peugeot', 'model' => '308', 'nadwozie' => 'SUV'],
            ['marka' => 'Peugeot', 'model' => '508', 'nadwozie' => 'Sedan'],
            ['marka' => 'Peugeot', 'model' => '508', 'nadwozie' => 'SUV'],
            ['marka' => 'Peugeot', 'model' => 'Partner', 'nadwozie' => 'Van'],
            ['marka' => 'Peugeot', 'model' => 'Expert', 'nadwozie' => 'Van'],
            ['marka' => 'Peugeot', 'model' => 'Boxer', 'nadwozie' => 'Van'],
            ['marka' => 'Peugeot', 'model' => 'Rifter', 'nadwozie' => 'MPV'],
            ['marka' => 'Renault', 'model' => 'Clio', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Renault', 'model' => 'Megane', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Renault', 'model' => 'Talisman', 'nadwozie' => 'Sedan'],
            ['marka' => 'Renault', 'model' => 'Captur', 'nadwozie' => 'SUV'],
            ['marka' => 'Renault', 'model' => 'Captur', 'nadwozie' => 'Van'],
            ['marka' => 'Renault', 'model' => 'Kadjar', 'nadwozie' => 'SUV'],
            ['marka' => 'Renault', 'model' => 'Kadjar', 'nadwozie' => 'Van'],
            ['marka' => 'Renault', 'model' => 'Koleos', 'nadwozie' => 'SUV'],
            ['marka' => 'Renault', 'model' => 'Kangoo', 'nadwozie' => 'SUV'],
            ['marka' => 'Renault', 'model' => 'Kangoo', 'nadwozie' => 'Van'],
            ['marka' => 'Renault', 'model' => 'Trafic', 'nadwozie' => 'Van'],
            ['marka' => 'Renault', 'model' => 'Master', 'nadwozie' => 'Van'],
            ['marka' => 'Renault', 'model' => 'Scenic', 'nadwozie' => 'MPV'],
            ['marka' => 'Opel', 'model' => 'Corsa', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Opel', 'model' => 'Astra', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Opel', 'model' => 'Insignia', 'nadwozie' => 'Sedan'],
            ['marka' => 'Opel', 'model' => 'Insignia', 'nadwozie' => 'SUV'],
            ['marka' => 'Opel', 'model' => 'Mokka', 'nadwozie' => 'SUV'],
            ['marka' => 'Opel', 'model' => 'Crossland', 'nadwozie' => 'SUV'],
            ['marka' => 'Opel', 'model' => 'Grandland', 'nadwozie' => 'SUV'],
            ['marka' => 'Opel', 'model' => 'Combo', 'nadwozie' => 'Van'],
            ['marka' => 'Opel', 'model' => 'Vivaro', 'nadwozie' => 'Van'],
            ['marka' => 'Opel', 'model' => 'Movano', 'nadwozie' => 'Van'],
            ['marka' => 'Opel', 'model' => 'Movano', 'nadwozie' => 'MPV'],
            ['marka' => 'Opel', 'model' => 'Zafira', 'nadwozie' => 'Van'],
            ['marka' => 'Opel', 'model' => 'Zafira', 'nadwozie' => 'MPV'],
            ['marka' => 'Isuzu', 'model' => 'D-Max', 'nadwozie' => 'Pickup'],
            ['marka' => 'Isuzu', 'model' => 'MU-X', 'nadwozie' => 'SUV'],
            ['marka' => 'Isuzu', 'model' => 'Trooper', 'nadwozie' => 'SUV'],
            ['marka' => 'Isuzu', 'model' => 'Rodeo', 'nadwozie' => 'Pickup'],
            ['marka' => 'Isuzu', 'model' => 'Ascender', 'nadwozie' => 'SUV'],
            ['marka' => 'Isuzu', 'model' => 'Axiom', 'nadwozie' => 'SUV'],
            ['marka' => 'Isuzu', 'model' => 'VehiCROSS', 'nadwozie' => 'SUV'],
            ['marka' => 'Isuzu', 'model' => 'i-Series', 'nadwozie' => 'Pickup'],
            ['marka' => 'Isuzu', 'model' => 'Gemini', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Isuzu', 'model' => 'Piazza', 'nadwozie' => 'Coupe'],
            ['marka' => 'Iveco', 'model' => 'Daily', 'nadwozie' => 'Van'],
            ['marka' => 'Iveco', 'model' => 'Eurocargo', 'nadwozie' => 'Truck'],
            ['marka' => 'Iveco', 'model' => 'Stralis', 'nadwozie' => 'Truck'],
            ['marka' => 'Iveco', 'model' => 'Trakker', 'nadwozie' => 'Truck'],
            ['marka' => 'Iveco', 'model' => 'PowerStar', 'nadwozie' => 'Truck'],
            ['marka' => 'Iveco', 'model' => 'TurboDaily', 'nadwozie' => 'Van'],
            ['marka' => 'Iveco', 'model' => 'Eurostar', 'nadwozie' => 'Truck'],
            ['marka' => 'Iveco', 'model' => 'Eurotrakker', 'nadwozie' => 'Truck'],
            ['marka' => 'Iveco', 'model' => 'Massif', 'nadwozie' => 'SUV'],
            ['marka' => 'Iveco', 'model' => 'Daily 4x4', 'nadwozie' => 'Van'],
            ['marka' => 'Alfa Romeo', 'model' => 'Giulia', 'nadwozie' => 'Sedan'],
            ['marka' => 'Alfa Romeo', 'model' => 'Giulia', 'nadwozie' => 'SUV'],
            ['marka' => 'Alfa Romeo', 'model' => 'Stelvio', 'nadwozie' => 'Sedan'],
            ['marka' => 'Alfa Romeo', 'model' => 'Stelvio', 'nadwozie' => 'SUV'],
            ['marka' => 'Alfa Romeo', 'model' => 'Giulietta', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Alfa Romeo', 'model' => '4C', 'nadwozie' => 'Coupe'],
            ['marka' => 'Alfa Romeo', 'model' => 'Tonale', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Alfa Romeo', 'model' => 'Tonale', 'nadwozie' => 'SUV'],
            ['marka' => 'Alfa Romeo', 'model' => 'Brera', 'nadwozie' => 'Coupe'],
            ['marka' => 'Alfa Romeo', 'model' => '159', 'nadwozie' => 'Sedan'],
            ['marka' => 'Alfa Romeo', 'model' => '159', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Alfa Romeo', 'model' => 'GT', 'nadwozie' => 'Coupe'],
            ['marka' => 'Alfa Romeo', 'model' => 'MiTo', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Alfa Romeo', 'model' => 'Spider', 'nadwozie' => 'Cabrio'],
            ['marka' => 'Alfa Romeo', 'model' => 'Spider', 'nadwozie' => 'Coupe'],
            ['marka' => 'Bentley', 'model' => 'Continental GT', 'nadwozie' => 'Coupe'],
            ['marka' => 'Bentley', 'model' => 'Flying Spur', 'nadwozie' => 'Sedan'],
            ['marka' => 'Bentley', 'model' => 'Bentayga', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Bentley', 'model' => 'Bentayga', 'nadwozie' => 'SUV'],
            ['marka' => 'Bentley', 'model' => 'Mulsanne', 'nadwozie' => 'Sedan'],
            ['marka' => 'Bentley', 'model' => 'Continental GTC', 'nadwozie' => 'Cabrio'],
            ['marka' => 'Bentley', 'model' => 'Arnage', 'nadwozie' => 'Sedan'],
            ['marka' => 'Bentley', 'model' => 'Brooklands', 'nadwozie' => 'Coupe'],
            ['marka' => 'Bentley', 'model' => 'Brooklands', 'nadwozie' => 'Cabrio'],
            ['marka' => 'Bentley', 'model' => 'Azure', 'nadwozie' => 'Coupe'],
            ['marka' => 'Bentley', 'model' => 'Azure', 'nadwozie' => 'Cabrio'],
            ['marka' => 'Bentley', 'model' => 'Turbo R', 'nadwozie' => 'Sedan'],
            ['marka' => 'Bentley', 'model' => 'Mulsanne Speed', 'nadwozie' => 'Sedan'],
            ['marka' => 'SsangYong', 'model' => 'Tivoli', 'nadwozie' => 'SUV'],
            ['marka' => 'SsangYong', 'model' => 'Korando', 'nadwozie' => 'SUV'],
            ['marka' => 'SsangYong', 'model' => 'Rexton', 'nadwozie' => 'SUV'],
            ['marka' => 'SsangYong', 'model' => 'Rexton', 'nadwozie' => 'Pickup'],
            ['marka' => 'SsangYong', 'model' => 'Musso', 'nadwozie' => 'SUV'],
            ['marka' => 'SsangYong', 'model' => 'Musso', 'nadwozie' => 'Pickup'],
            ['marka' => 'SsangYong', 'model' => 'Actyon', 'nadwozie' => 'SUV'],
            ['marka' => 'SsangYong', 'model' => 'XLV', 'nadwozie' => 'SUV'],
            ['marka' => 'SsangYong', 'model' => 'Kyron', 'nadwozie' => 'SUV'],
            ['marka' => 'SsangYong', 'model' => 'Kyron', 'nadwozie' => 'Pickup'],
            ['marka' => 'SsangYong', 'model' => 'Rodius', 'nadwozie' => 'MPV'],
            ['marka' => 'SsangYong', 'model' => 'Rodius', 'nadwozie' => 'Pickup'],
            ['marka' => 'SsangYong', 'model' => 'Korando Sports', 'nadwozie' => 'Pickup'],
            ['marka' => 'Suzuki', 'model' => 'Swift', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Suzuki', 'model' => 'Vitara', 'nadwozie' => 'SUV'],
            ['marka' => 'Suzuki', 'model' => 'Jimny', 'nadwozie' => 'SUV'],
            ['marka' => 'Suzuki', 'model' => 'Ignis', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Suzuki', 'model' => 'S-Cross', 'nadwozie' => 'SUV'],
            ['marka' => 'Suzuki', 'model' => 'Baleno', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Suzuki', 'model' => 'SX4', 'nadwozie' => 'Sedan'],
            ['marka' => 'Suzuki', 'model' => 'Celerio', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Suzuki', 'model' => 'Splash', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Suzuki', 'model' => 'Grand Vitara', 'nadwozie' => 'SUV'],
            ['marka' => 'Porsche', 'model' => '911', 'nadwozie' => 'Coupe'],
            ['marka' => 'Porsche', 'model' => '911', 'nadwozie' => 'Cabrio'],
            ['marka' => 'Porsche', 'model' => 'Cayenne', 'nadwozie' => 'SUV'],
            ['marka' => 'Porsche', 'model' => 'Panamera', 'nadwozie' => 'Sedan'],
            ['marka' => 'Porsche', 'model' => 'Panamera', 'nadwozie' => 'Coupe'],
            ['marka' => 'Porsche', 'model' => 'Macan', 'nadwozie' => 'SUV'],
            ['marka' => 'Porsche', 'model' => 'Boxster', 'nadwozie' => 'Cabrio'],
            ['marka' => 'Porsche', 'model' => 'Cayman', 'nadwozie' => 'Coupe'],
            ['marka' => 'Porsche', 'model' => 'Cayman', 'nadwozie' => 'Cabrio'],
            ['marka' => 'Porsche', 'model' => 'Cayman', 'nadwozie' => 'Sedan'],
            ['marka' => 'Porsche', 'model' => 'Taycan', 'nadwozie' => 'Sedan'],
            ['marka' => 'Porsche', 'model' => '718', 'nadwozie' => 'Cabrio'],
            ['marka' => 'Porsche', 'model' => '718', 'nadwozie' => 'Coupe'],
            ['marka' => 'Dodge', 'model' => 'Charger', 'nadwozie' => 'Sedan'],
            ['marka' => 'Dodge', 'model' => 'Challenger', 'nadwozie' => 'Coupe'],
            ['marka' => 'Dodge', 'model' => 'Durango', 'nadwozie' => 'SUV'],
            ['marka' => 'Dodge', 'model' => 'Durango', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Dodge', 'model' => 'Durango', 'nadwozie' => 'Van'],
            ['marka' => 'Dodge', 'model' => 'Journey', 'nadwozie' => 'SUV'],
            ['marka' => 'Dodge', 'model' => 'Journey', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Dodge', 'model' => 'Grand Caravan', 'nadwozie' => 'Van'],
            ['marka' => 'Dodge', 'model' => 'Avenger', 'nadwozie' => 'Sedan'],
            ['marka' => 'Dodge', 'model' => 'Dart', 'nadwozie' => 'Sedan'],
            ['marka' => 'Dodge', 'model' => 'Dart', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Dodge', 'model' => 'Nitro', 'nadwozie' => 'SUV'],
            ['marka' => 'Dodge', 'model' => 'Caliber', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Dodge', 'model' => 'Magnum', 'nadwozie' => 'Wagon'],
            ['marka' => 'Ferrari', 'model' => '488 GTB', 'nadwozie' => 'Coupe'],
            ['marka' => 'Ferrari', 'model' => '812 Superfast', 'nadwozie' => 'Coupe'],
            ['marka' => 'Ferrari', 'model' => 'F8 Tributo', 'nadwozie' => 'Coupe'],
            ['marka' => 'Ferrari', 'model' => 'SF90 Stradale', 'nadwozie' => 'Coupe'],
            ['marka' => 'Ferrari', 'model' => 'Roma', 'nadwozie' => 'Coupe'],
            ['marka' => 'Ferrari', 'model' => 'Portofino', 'nadwozie' => 'Cabrio'],
            ['marka' => 'Ferrari', 'model' => 'GTC4Lusso', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Ferrari', 'model' => 'Monza SP1', 'nadwozie' => 'Roadster'],
            ['marka' => 'Ferrari', 'model' => '458 Italia', 'nadwozie' => 'Coupe'],
            ['marka' => 'Ferrari', 'model' => 'LaFerrari', 'nadwozie' => 'Coupe'],
            ['marka' => 'Jaguar', 'model' => 'XE', 'nadwozie' => 'Sedan'],
            ['marka' => 'Jaguar', 'model' => 'XF', 'nadwozie' => 'Sedan'],
            ['marka' => 'Jaguar', 'model' => 'XJ', 'nadwozie' => 'Sedan'],
            ['marka' => 'Jaguar', 'model' => 'F-Type', 'nadwozie' => 'Coupe'],
            ['marka' => 'Jaguar', 'model' => 'F-Type', 'nadwozie' => 'SUV'],
            ['marka' => 'Jaguar', 'model' => 'F-Type', 'nadwozie' => 'Sedan'],
            ['marka' => 'Jaguar', 'model' => 'E-Pace', 'nadwozie' => 'Coupe'],
            ['marka' => 'Jaguar', 'model' => 'E-Pace', 'nadwozie' => 'SUV'],
            ['marka' => 'Jaguar', 'model' => 'E-Pace', 'nadwozie' => 'Sedan'],
            ['marka' => 'Jaguar', 'model' => 'I-Pace', 'nadwozie' => 'Coupe'],
            ['marka' => 'Jaguar', 'model' => 'I-Pace', 'nadwozie' => 'SUV'],
            ['marka' => 'Jaguar', 'model' => 'I-Pace', 'nadwozie' => 'Sedan'],
            ['marka' => 'Jaguar', 'model' => 'X-Type', 'nadwozie' => 'Coupe'],
            ['marka' => 'Jaguar', 'model' => 'X-Type', 'nadwozie' => 'SUV'],
            ['marka' => 'Jaguar', 'model' => 'X-Type', 'nadwozie' => 'Sedan'],
            ['marka' => 'Jaguar', 'model' => 'S-Type', 'nadwozie' => 'Coupe'],
            ['marka' => 'Jaguar', 'model' => 'S-Type', 'nadwozie' => 'SUV'],
            ['marka' => 'Jaguar', 'model' => 'S-Type', 'nadwozie' => 'Sedan'],
            ['marka' => 'Jeep', 'model' => 'Wrangler', 'nadwozie' => 'SUV'],
            ['marka' => 'Jeep', 'model' => 'Grand Cherokee', 'nadwozie' => 'SUV'],
            ['marka' => 'Jeep', 'model' => 'Cherokee', 'nadwozie' => 'SUV'],
            ['marka' => 'Jeep', 'model' => 'Compass', 'nadwozie' => 'SUV'],
            ['marka' => 'Jeep', 'model' => 'Renegade', 'nadwozie' => 'SUV'],
            ['marka' => 'Jeep', 'model' => 'Commander', 'nadwozie' => 'SUV'],
            ['marka' => 'Jeep', 'model' => 'Patriot', 'nadwozie' => 'SUV'],
            ['marka' => 'Jeep', 'model' => 'Liberty', 'nadwozie' => 'SUV'],
            ['marka' => 'Jeep', 'model' => 'Liberty', 'nadwozie' => 'Pickup'],
            ['marka' => 'Jeep', 'model' => 'Wagoneer', 'nadwozie' => 'SUV'],
            ['marka' => 'Jeep', 'model' => 'Wagoneer', 'nadwozie' => 'Pickup'],
            ['marka' => 'Jeep', 'model' => 'Gladiator', 'nadwozie' => 'SUV'],
            ['marka' => 'Jeep', 'model' => 'Gladiator', 'nadwozie' => 'Pickup'],
            ['marka' => 'Cupra', 'model' => 'Leon', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Cupra', 'model' => 'Ateca', 'nadwozie' => 'SUV'],
            ['marka' => 'Cupra', 'model' => 'Ateca', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Cupra', 'model' => 'Formentor', 'nadwozie' => 'SUV'],
            ['marka' => 'Cupra', 'model' => 'Leon', 'nadwozie' => 'Wagon'],
            ['marka' => 'Cupra', 'model' => 'Leon', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Cupra', 'model' => 'Ateca Limited Edition', 'nadwozie' => 'SUV'],
            ['marka' => 'Cupra', 'model' => 'Leon Cupra', 'nadwozie' => 'Wagon'],
            ['marka' => 'Cupra', 'model' => 'Leon Cupra', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Cupra', 'model' => 'Formentor VZ5', 'nadwozie' => 'SUV'],
            ['marka' => 'Cupra', 'model' => 'Leon ST', 'nadwozie' => 'Wagon'],
            ['marka' => 'Mini', 'model' => 'Cooper', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Mini', 'model' => 'Cooper', 'nadwozie' => 'SUV'],
            ['marka' => 'Mini', 'model' => 'Countryman', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Mini', 'model' => 'Countryman', 'nadwozie' => 'SUV'],
            ['marka' => 'Mini', 'model' => 'Clubman', 'nadwozie' => 'Wagon'],
            ['marka' => 'Mini', 'model' => 'Convertible', 'nadwozie' => 'Cabrio'],
            ['marka' => 'Mini', 'model' => 'Paceman', 'nadwozie' => 'SUV'],
            ['marka' => 'Mini', 'model' => 'Coupe', 'nadwozie' => 'Coupe'],
            ['marka' => 'Mini', 'model' => 'Roadster', 'nadwozie' => 'Cabrio'],
            ['marka' => 'Mini', 'model' => 'Roadster', 'nadwozie' => 'Coupe'],
            ['marka' => 'Mini', 'model' => 'Roadster', 'nadwozie' => 'Sedan'],
            ['marka' => 'Mini', 'model' => 'Hardtop', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Mini', 'model' => 'Hardtop', 'nadwozie' => 'SUV'],
            ['marka' => 'Mini', 'model' => 'John Cooper Works', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Fiat', 'model' => '500', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Fiat', 'model' => '500', 'nadwozie' => 'SUV'],
            ['marka' => 'Fiat', 'model' => '500', 'nadwozie' => 'MPV'],
            ['marka' => 'Fiat', 'model' => 'Panda', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Fiat', 'model' => 'Tipo', 'nadwozie' => 'Sedan'],
            ['marka' => 'Fiat', 'model' => 'Punto', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Fiat', 'model' => 'Doblo', 'nadwozie' => 'Van'],
            ['marka' => 'Fiat', 'model' => 'Qubo', 'nadwozie' => 'Van'],
            ['marka' => 'Fiat', 'model' => 'Talento', 'nadwozie' => 'Van'],
            ['marka' => 'Kia', 'model' => 'Rio', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Kia', 'model' => 'Rio', 'nadwozie' => 'SUV'],
            ['marka' => 'Kia', 'model' => 'Ceed', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Kia', 'model' => 'Ceed', 'nadwozie' => 'SUV'],
            ['marka' => 'Kia', 'model' => 'Forte', 'nadwozie' => 'Sedan'],
            ['marka' => 'Kia', 'model' => 'Optima', 'nadwozie' => 'Coupe'],
            ['marka' => 'Kia', 'model' => 'Optima', 'nadwozie' => 'Sedan'],
            ['marka' => 'Kia', 'model' => 'Stinger', 'nadwozie' => 'Coupe'],
            ['marka' => 'Kia', 'model' => 'Stinger', 'nadwozie' => 'Sedan'],
            ['marka' => 'Kia', 'model' => 'Sportage', 'nadwozie' => 'SUV'],
            ['marka' => 'Kia', 'model' => 'Seltos', 'nadwozie' => 'SUV'],
            ['marka' => 'Kia', 'model' => 'Soul', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Kia', 'model' => 'Telluride', 'nadwozie' => 'SUV'],
            ['marka' => 'Nissan', 'model' => 'Altima', 'nadwozie' => 'Sedan'],
            ['marka' => 'Nissan', 'model' => 'Sentra', 'nadwozie' => 'Sedan'],
            ['marka' => 'Nissan', 'model' => 'Maxima', 'nadwozie' => 'Sedan'],
            ['marka' => 'Nissan', 'model' => 'Altima', 'nadwozie' => 'Coupe'],
            ['marka' => 'Nissan', 'model' => 'Sentra', 'nadwozie' => 'Coupe'],
            ['marka' => 'Nissan', 'model' => 'Maxima', 'nadwozie' => 'Coupe'],
            ['marka' => 'Nissan', 'model' => 'Altima', 'nadwozie' => 'Cabrio'],
            ['marka' => 'Nissan', 'model' => 'Sentra', 'nadwozie' => 'Cabrio'],
            ['marka' => 'Nissan', 'model' => 'Maxima', 'nadwozie' => 'Cabrio'],
            ['marka' => 'Nissan', 'model' => 'Micra', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Nissan', 'model' => 'Micra', 'nadwozie' => 'SUV'],
            ['marka' => 'Nissan', 'model' => 'Rogue', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Nissan', 'model' => 'Rogue', 'nadwozie' => 'SUV'],
            ['marka' => 'Nissan', 'model' => 'Murano', 'nadwozie' => 'SUV'],
            ['marka' => 'Nissan', 'model' => 'Pathfinder', 'nadwozie' => 'SUV'],
            ['marka' => 'Nissan', 'model' => 'Armada', 'nadwozie' => 'SUV'],
            ['marka' => 'Nissan', 'model' => 'Leaf', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Nissan', 'model' => 'Leaf', 'nadwozie' => 'SUV'],
            ['marka' => 'Citroen', 'model' => 'C3', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Citroen', 'model' => 'C3', 'nadwozie' => 'Sedan'],
            ['marka' => 'Citroen', 'model' => 'C3', 'nadwozie' => 'SUV'],
            ['marka' => 'Citroen', 'model' => 'C4', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Citroen', 'model' => 'C4', 'nadwozie' => 'Sedan'],
            ['marka' => 'Citroen', 'model' => 'C4', 'nadwozie' => 'SUV'],
            ['marka' => 'Citroen', 'model' => 'C5', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Citroen', 'model' => 'C5', 'nadwozie' => 'Sedan'],
            ['marka' => 'Citroen', 'model' => 'C5', 'nadwozie' => 'SUV'],
            ['marka' => 'Citroen', 'model' => 'Berlingo', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Citroen', 'model' => 'Berlingo', 'nadwozie' => 'Van'],
            ['marka' => 'Citroen', 'model' => 'DS3', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Citroen', 'model' => 'DS4', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Citroen', 'model' => 'DS5', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Dacia', 'model' => 'Sandero', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Dacia', 'model' => 'Logan', 'nadwozie' => 'Sedan'],
            ['marka' => 'Dacia', 'model' => 'Duster', 'nadwozie' => 'SUV'],
            ['marka' => 'Dacia', 'model' => 'Dokker', 'nadwozie' => 'Van'],
            ['marka' => 'Dacia', 'model' => 'Lodgy', 'nadwozie' => 'MPV'],
            ['marka' => 'Mercedes-Benz', 'model' => 'C-Class', 'nadwozie' => 'Sedan'],
            ['marka' => 'Mercedes-Benz', 'model' => 'E-Class', 'nadwozie' => 'Sedan'],
            ['marka' => 'Mercedes-Benz', 'model' => 'S-Class', 'nadwozie' => 'Sedan'],
            ['marka' => 'Mercedes-Benz', 'model' => 'A-Class', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Mercedes-Benz', 'model' => 'A-Class', 'nadwozie' => 'SUV'],
            ['marka' => 'Mercedes-Benz', 'model' => 'G-Class', 'nadwozie' => 'Hatchback'],
            ['marka' => 'Mercedes-Benz', 'model' => 'G-Class', 'nadwozie' => 'SUV'],
            ['marka' => 'Mercedes-Benz', 'model' => 'CLA-Class', 'nadwozie' => 'Coupe'],
            ['marka' => 'Mercedes-Benz', 'model' => 'GLA-Class', 'nadwozie' => 'SUV'],
            ['marka' => 'Mercedes-Benz', 'model' => 'GLC-Class', 'nadwozie' => 'Coupe'],
            ['marka' => 'Mercedes-Benz', 'model' => 'GLC-Class', 'nadwozie' => 'SUV'],
            ['marka' => 'Mercedes-Benz', 'model' => 'GLE-Class', 'nadwozie' => 'Coupe'],
            ['marka' => 'Mercedes-Benz', 'model' => 'GLE-Class', 'nadwozie' => 'SUV'],
            ['marka' => 'Mercedes-Benz', 'model' => 'GLS-Class', 'nadwozie' => 'Coupe'],
            ['marka' => 'Mercedes-Benz', 'model' => 'GLS-Class', 'nadwozie' => 'SUV'],
        ];

        foreach ($poczatkoweDane as $dane) {
            CechyPojazdu::firstOrCreate($dane);
        }
    }
}
