<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Kraj;

class KrajeTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $poczatkoweDane = [
            ['nazwa' => 'Afganistan'],
            ['nazwa' => 'Albania'],
            ['nazwa' => 'Algieria'],
            ['nazwa' => 'Andora'],
            ['nazwa' => 'Angola'],
            ['nazwa' => 'Antigua i Barbuda'],
            ['nazwa' => 'Arabia Saudyjska'],
            ['nazwa' => 'Argentyna'],
            ['nazwa' => 'Armenia'],
            ['nazwa' => 'Australia'],
            ['nazwa' => 'Austria'],
            ['nazwa' => 'Azerbejdżan'],
            ['nazwa' => 'Bahamy'],
            ['nazwa' => 'Bahrajn'],
            ['nazwa' => 'Bangladesz'],
            ['nazwa' => 'Barbados'],
            ['nazwa' => 'Belgia'],
            ['nazwa' => 'Belize'],
            ['nazwa' => 'Benin'],
            ['nazwa' => 'Bhutan'],
            ['nazwa' => 'Białoruś'],
            ['nazwa' => 'Boliwia'],
            ['nazwa' => 'Bośnia i Hercegowina'],
            ['nazwa' => 'Botswana'],
            ['nazwa' => 'Brazylia'],
            ['nazwa' => 'Brunei'],
            ['nazwa' => 'Bułgaria'],
            ['nazwa' => 'Burkina Faso'],
            ['nazwa' => 'Burundi'],
            ['nazwa' => 'Chile'],
            ['nazwa' => 'Chiny'],
            ['nazwa' => 'Chorwacja'],
            ['nazwa' => 'Cypr'],
            ['nazwa' => 'Czad'],
            ['nazwa' => 'Czarnogóra'],
            ['nazwa' => 'Czechy'],
            ['nazwa' => 'Dania'],
            ['nazwa' => 'Demokratyczna Republika Konga'],
            ['nazwa' => 'Dominika'],
            ['nazwa' => 'Dominikana'],
            ['nazwa' => 'Dżibuti'],
            ['nazwa' => 'Egipt'],
            ['nazwa' => 'Ekwador'],
            ['nazwa' => 'Erytrea'],
            ['nazwa' => 'Estonia'],
            ['nazwa' => 'Eswatini'],
            ['nazwa' => 'Etiopia'],
            ['nazwa' => 'Fidżi'],
            ['nazwa' => 'Filipiny'],
            ['nazwa' => 'Finlandia'],
            ['nazwa' => 'Francja'],
            ['nazwa' => 'Gabon'],
            ['nazwa' => 'Gambia'],
            ['nazwa' => 'Ghana'],
            ['nazwa' => 'Grecja'],
            ['nazwa' => 'Grenada'],
            ['nazwa' => 'Gruzja'],
            ['nazwa' => 'Gujana'],
            ['nazwa' => 'Gwatemala'],
            ['nazwa' => 'Gwinea'],
            ['nazwa' => 'Gwinea Bissau'],
            ['nazwa' => 'Gwinea Równikowa'],
            ['nazwa' => 'Haiti'],
            ['nazwa' => 'Hiszpania'],
            ['nazwa' => 'Holandia'],
            ['nazwa' => 'Honduras'],
            ['nazwa' => 'Indie'],
            ['nazwa' => 'Indonezja'],
            ['nazwa' => 'Irak'],
            ['nazwa' => 'Iran'],
            ['nazwa' => 'Irlandia'],
            ['nazwa' => 'Islandia'],
            ['nazwa' => 'Izrael'],
            ['nazwa' => 'Jamajka'],
            ['nazwa' => 'Japonia'],
            ['nazwa' => 'Jemen'],
            ['nazwa' => 'Jordania'],
            ['nazwa' => 'Kambodża'],
            ['nazwa' => 'Kamerun'],
            ['nazwa' => 'Kanada'],
            ['nazwa' => 'Katar'],
            ['nazwa' => 'Kazachstan'],
            ['nazwa' => 'Kenia'],
            ['nazwa' => 'Kirgistan'],
            ['nazwa' => 'Kiribati'],
            ['nazwa' => 'Kolumbia'],
            ['nazwa' => 'Komory'],
            ['nazwa' => 'Kongo'],
            ['nazwa' => 'Korea Południowa'],
            ['nazwa' => 'Korea Północna'],
            ['nazwa' => 'Kostaryka'],
            ['nazwa' => 'Kuba'],
            ['nazwa' => 'Kuwejt'],
            ['nazwa' => 'Laos'],
            ['nazwa' => 'Lesotho'],
            ['nazwa' => 'Liban'],
            ['nazwa' => 'Liberia'],
            ['nazwa' => 'Libia'],
            ['nazwa' => 'Liechtenstein'],
            ['nazwa' => 'Litwa'],
            ['nazwa' => 'Luksemburg'],
            ['nazwa' => 'Łotwa'],
            ['nazwa' => 'Macedonia Północna'],
            ['nazwa' => 'Madagaskar'],
            ['nazwa' => 'Malawi'],
            ['nazwa' => 'Malediwy'],
            ['nazwa' => 'Malezja'],
            ['nazwa' => 'Mali'],
            ['nazwa' => 'Malta'],
            ['nazwa' => 'Maroko'],
            ['nazwa' => 'Mauretania'],
            ['nazwa' => 'Mauritius'],
            ['nazwa' => 'Meksyk'],
            ['nazwa' => 'Mikronezja'],
            ['nazwa' => 'Mołdawia'],
            ['nazwa' => 'Monako'],
            ['nazwa' => 'Mongolia'],
            ['nazwa' => 'Mozambik'],
            ['nazwa' => 'Namibia'],
            ['nazwa' => 'Nauru'],
            ['nazwa' => 'Nepal'],
            ['nazwa' => 'Niemcy'],
            ['nazwa' => 'Niger'],
            ['nazwa' => 'Nigeria'],
            ['nazwa' => 'Nikaragua'],
            ['nazwa' => 'Norwegia'],
            ['nazwa' => 'Nowa Zelandia'],
            ['nazwa' => 'Oman'],
            ['nazwa' => 'Pakistan'],
            ['nazwa' => 'Palau'],
            ['nazwa' => 'Panama'],
            ['nazwa' => 'Papua-Nowa Gwinea'],
            ['nazwa' => 'Paragwaj'],
            ['nazwa' => 'Peru'],
            ['nazwa' => 'Polska'],
            ['nazwa' => 'Portugalia'],
            ['nazwa' => 'Republika Południowej Afryki'],
            ['nazwa' => 'Republika Środkowoafrykańska'],
            ['nazwa' => 'Republika Zielonego Przylądka'],
            ['nazwa' => 'Rosja'],
            ['nazwa' => 'Rumunia'],
            ['nazwa' => 'Rwanda'],
            ['nazwa' => 'Saint Kitts i Nevis'],
            ['nazwa' => 'Saint Lucia'],
            ['nazwa' => 'Saint Vincent i Grenadyny'],
            ['nazwa' => 'Salwador'],
            ['nazwa' => 'Samoa'],
            ['nazwa' => 'San Marino'],
            ['nazwa' => 'Senegal'],
            ['nazwa' => 'Serbia'],
            ['nazwa' => 'Seszele'],
            ['nazwa' => 'Sierra Leone'],
            ['nazwa' => 'Singapur'],
            ['nazwa' => 'Słowacja'],
            ['nazwa' => 'Słowenia'],
            ['nazwa' => 'Somalia'],
            ['nazwa' => 'Sri Lanka'],
            ['nazwa' => 'Sudan'],
            ['nazwa' => 'Sudan Południowy'],
            ['nazwa' => 'Surinam'],
            ['nazwa' => 'Syria'],
            ['nazwa' => 'Szwajcaria'],
            ['nazwa' => 'Szwecja'],
            ['nazwa' => 'Tadżykistan'],
            ['nazwa' => 'Tajlandia'],
            ['nazwa' => 'Tanzania'],
            ['nazwa' => 'Timor Wschodni'],
            ['nazwa' => 'Togo'],
            ['nazwa' => 'Tonga'],
            ['nazwa' => 'Trynidad i Tobago'],
            ['nazwa' => 'Tunezja'],
            ['nazwa' => 'Turcja'],
            ['nazwa' => 'Turkmenistan'],
            ['nazwa' => 'Tuvalu'],
            ['nazwa' => 'Uganda'],
            ['nazwa' => 'Ukraina'],
            ['nazwa' => 'Urugwaj'],
            ['nazwa' => 'Uzbekistan'],
            ['nazwa' => 'Vanuatu'],
            ['nazwa' => 'Watykan'],
            ['nazwa' => 'Wenezuela'],
            ['nazwa' => 'Węgry'],
            ['nazwa' => 'Wielka Brytania'],
            ['nazwa' => 'Wietnam'],
            ['nazwa' => 'Włochy'],
            ['nazwa' => 'Wybrzeże Kości Słoniowej'],
            ['nazwa' => 'Wyspy Marshalla'],
            ['nazwa' => 'Wyspy Salomona'],
            ['nazwa' => 'Wyspy Świętego Tomasza i Książęca'],
            ['nazwa' => 'Zambia'],
            ['nazwa' => 'Zimbabwe'],
        ];

        foreach ($poczatkoweDane as $dane) {
            Kraj::firstOrCreate([
                'nazwa' => $dane['nazwa'],
            ], []);
        }
    }
}
